name: application
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: 1.8.1
  get: 4.6.6
  flutter_secure_storage: ^9.0.0
  get_storage: ^2.1.1
  dio: ^5.3.3
  http: 0.13.6
  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: 
  slide_countdown: ^1.1.0
  linear_timer: ^2.0.0
  liquid_progress_indicator_v2: ^0.5.0
  intl: ^0.18.1
  image_network: ^2.5.4+1
  image_picker: ^1.0.4
  dropdown_button2: ^2.3.9
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/Images/
  #fonts: 
   # - family: Montserrat
   #   fonts :
    #    - asset: font/Montserrat-VariableFont_wght
          
